### ISSUE TITLE
Extremely slow after working on a large file for a while

### ISSUE THREAD

**Issue by teppah** [ShazzAmin/Boole#67]
The editor slows down noticeably after editing a large (200+ line) file for a bit to the point where typing a character takes a couple of seconds. Occasionally, the whole webpage also completely hangs. 

It may have something to do with snippet expansion/autocompletion from https://github.com/ShazzAmin/Boole/pull/66, or it might be an earlier dependency bump that's causing the problem.

**Comment by ShazzAmin** [comment]
I believe this is fixed now. It was likely as a result of a dependency bump from #66 as you mentioned.
